/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        lexend: ['Lexend', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
      },
      colors: {
        primary: '#006e2f',
        'on-primary': '#ffffff',
        'primary-container': '#22c55e',
        'on-primary-container': '#002109',
        'primary-fixed': '#76df85',
        'primary-fixed-dim': '#58c26b',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005323',
        secondary: '#516351',
        'on-secondary': '#ffffff',
        'secondary-container': '#d4e8d0',
        'on-secondary-container': '#0f1f11',
        tertiary: '#39656d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bce9f2',
        'on-tertiary-container': '#001f24',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        surface: '#f8f9ff',
        'on-surface': '#191c20',
        'surface-variant': '#dde5da',
        'on-surface-variant': '#414941',
        outline: '#717970',
        'outline-variant': '#c1c9bf',
        shadow: '#000000',
        scrim: '#000000',
        'inverse-surface': '#2e3035',
        'inverse-on-surface': '#eff0f7',
        'inverse-primary': '#58c26b',
        'surface-container-highest': '#e5e5ec',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e5eeff',
        'surface-container-low': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#d9dae0',
      },
      boxShadow: {
        'soft': '0 8px 30px rgba(34, 197, 94, 0.08)',
        'soft-lg': '0 20px 60px rgba(34, 197, 94, 0.12)',
        'nav': '20px 0 40px -10px rgba(34, 197, 94, 0.04)',
      },
    },
  },
  plugins: [],
}
